name: autoytpoo
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch==2.2.0
  - pytorch-cuda=12.1
  - torchvision=0.17.0
  - torchaudio==2.2.0
  - numpy==1.26.3
  - pip:
      - albumentations==1.3.0
      - opencv-python==4.6.0.66
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning==1.4.2
      - omegaconf==2.1.1
      - test-tube>=0.7.5
      - streamlit==1.12.1
      - einops==0.6.0
      - webdataset==0.2.5
      - kornia==0.6
      - open_clip_torch==2.0.2
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==0.6.0
      - tokenizers==0.14.1
      - scikit-learn==1.4.0
      - safetensors==0.4.2
      - diffusers==0.23.1
      - transformers
      - accelerate==0.26.1
      - git+https://github.com/coqui-ai/TTS.git
